### ISSUE TITLE
EBCDIC to Decode Problem:

### ISSUE THREAD

**Issue by FarhadF** [gdamore/encoding#5]
When Im trying to `enc.EBCDIC.NewDecoder().String(string(rec2))` I get 
![image](https://user-images.githubusercontent.com/17374492/34093640-954a96b0-e3de-11e7-91bf-5f5c162ff42f.png)
The square boxes should be spaces. Here is the desired output.
![image](https://user-images.githubusercontent.com/17374492/34093671-b75ebe34-e3de-11e7-984d-b3e334773113.png)
Even when I copy the boxes into a text editor they get translated to spaces. I cant do string parsing on such characters. It would be amazing if you could guide me into the right direction.

Update: The byte array I'm receiving:
[0 0 0 198 195 240 240 240 240 240 241 195 228 214 214 0 0 0 0 0 0 0 0 241 243 249 246 240 249 242 247 241 240 244 246 245 242 240]

The boxes are these zeroes...

Thanks for the amazing package.

**Comment by FarhadF** [comment]
I've added `0x00: ' ',` at the beginning of the map in ebcdic.go and the issue is fixed.
```
Map: map[byte]rune{
			// 0x00-0x03 match
			0x00: ' ',
			0x04: RuneError,
```

Is this standard? Should I open a pull request?

**Comment by gdamore** [comment]
Huh.  I'm not sure 0 should be encoded as a space.  I used this as the source material: https://en.wikipedia.org/wiki/EBCDIC

I don't regularly have to deal with EBCDIC.

Are you sure that your source material is actual character data?  My first guess is that your material isn't exactly what you think it is, and that those NUL bytes are actually conveying some other meaning, like a field delimiter.

**Comment by gdamore** [comment]
Specifically, also it appears than ebcdic space character should have numeric value 0x40 (64 decimal).

**Comment by FarhadF** [comment]
You are right man, I reviewed the ebcdic doc on IBM website, and indeed space is 0x40, I believe Mainframe guys in my environment are not using standard. Thanks for the info.

**Comment by gdamore** [comment]
You should try to discover why they are sending NUL bytes. I suspect that
they are intended to convey some meaning that has gotten lost somewhere.
Best of luck to you.
